### ISSUE TITLE
Not working on osx

### ISSUE THREAD

**Issue by xa-bi** [adder46/hstr-rs#10]
```
> RUST_BACKTRACE=1 hstr-rs

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }', hstr/src/app.rs:40:69
stack backtrace:
0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
1: core::fmt::write
2: std::io::Write::write_fmt
3: std::panicking::default_hook::{{closure}}
4: std::panicking::default_hook
5: std::panicking::rust_panic_with_hook
6: rust_begin_unwind
7: core::panicking::panic_fmt
8: core::result::unwrap_failed
9: hstr_rs::app::Application::load_commands
10: hstr_rs::main
11: std::rt::lang_start::{{closure}}
12: std::rt::lang_start_internal
13: main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Some info:

- Installed via `cargo install --git https://github.com/adder46/hstr-rs.git`
- OS Version: `Darwin mb.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`
- `-rw-------  1 xabi  staff  874801 Dec 28 08:54 .zsh_history`

**Comment by adder46** [comment]
Unfortunately, I'll have to seek help regarding this issue since I do not have access to Mac hardware, and, as we know, installing Apple software in a virtual machine on non-Apple hardware is considered piracy.

**Comment by zaps** [comment]
Github Actions provides a macOS [virtual environment](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) for doing builds.

I’ve been playing around with this in my [fork](https://github.com/zaps/hstr-rs), unfortunately I don’t know enough about how to configure rust/cargo to use native libraries (in this case ncurses/w) in the build.

Perhaps someone can provide advice based on the error messages in the various builds.

Thanks!
