### ISSUE TITLE
Backspace produces ^? when hstr-rs is run from tmux

### ISSUE THREAD

**Issue by alopatindev** [adder46/hstr-rs#13]
tmux 3.1b
xterm 351

**Comment by adder46** [comment]
Might be relatated: [link](https://unix.stackexchange.com/questions/139075/tmux-ncurses-apps-are-displayed-wrong-with-garbage-and-so-on).

**Comment by adder46** [comment]
I installed `tmux` on Ubuntu 20.04 via `apt install tmux`, I tested hstr-rs in xfce4-terminal, xterm, and linux term. I was not able to reproduce the issue. Indeed, `echo $TERM` returned `screen`. So, set your `$TERM` to `screen` when inside `tmux` and you should be good to go. Note that I did not have to set anything manually, something already did it for me.
