### ISSUE TITLE
(question) can this be configured like the original "hstr"?

### ISSUE THREAD

**Issue by 5c0tt-b0t** [adder46/hstr-rs#16]
The original "hstr" allows `hstr --show-config` which can be copy & pasted or echo'ed to .bashrc and modified, running `hstr-rs --show-config` doesnt show anything, so does this expect a configuration/startup file somewhere? if not how would I configure this?

**Thank you!**

**Comment by adder46** [comment]
If you're on bash, it's recommended that you add the lines below in your `~/.bashrc`:

```sh
# append new history items to .bash_history
shopt -s histappend 
# don't put duplicate lines or lines starting with space in the history
HISTCONTROL=ignoreboth
# increase history file size
HISTFILESIZE=1000000
# increase history size
HISTSIZE=${HISTFILESIZE}
# append new entries from memory to .bash_history
export PROMPT_COMMAND="history -a; history -n; ${PROMPT_COMMAND}"
```

(Copy/paste from `README.md`)

At the moment, there are no command-line options or arguments that you can pass to hstr-rs, however, I was thinking of adding the `--show-config` option or something like that, which would basically print the lines above, enabling you to pass the output to the shell rc file.
