### ISSUE TITLE
Publish Pre-Built Libraries

### ISSUE THREAD

**Issue by nikeee** [adder46/hstr-rs#17]
It would be nice to have some binaries pre-built for some OSes (like Ubuntu/Debian).

**Comment by adder46** [comment]
I released a pre-built binary for Ubuntu/Debian, meaning you can install hstr-rs using:

```sh
curl -LO https://github.com/adder46/hstr-rs/releases/download/v0.8.0/hstr-rs_0.8.0_amd64.deb
sudo dpkg -i hstr-rs_0.8.0_amd64.deb
```
